Add repro test
org.apache.cassandra.distributed.shared.ShutdownException: Uncaught exceptions were thrown during test
	at org.apache.cassandra.distributed.impl.AbstractCluster.checkAndResetUncaughtExceptions(AbstractCluster.java:1151)
	at org.apache.cassandra.distributed.impl.AbstractCluster.close(AbstractCluster.java:1136)
	at org.apache.cassandra.distributed.test.tracking.MutationTrackingWriteForwardingTest.testBasicWriteForwarding(MutationTrackingWriteForwardingTest.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
	Suppressed: java.lang.RuntimeException: java.lang.AssertionError: Callback already exists for id 42//127.0.0.2:7012! ({peer:/127.0.0.2:7012, callback:org.apache.cassandra.service.WriteResponseHandler@d6593e7, invokeOnFailure:true})
		at org.apache.cassandra.net.InboundSink.accept(InboundSink.java:146)
		at org.apache.cassandra.net.InboundSink.accept(InboundSink.java:52)
		at org.apache.cassandra.net.InboundMessageHandler$ProcessMessage.run(InboundMessageHandler.java:448)
		at org.apache.cassandra.concurrent.ExecutionFailure$1.run(ExecutionFailure.java:133)
		at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:145)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.lang.AssertionError: Callback already exists for id 42//127.0.0.2:7012! ({peer:/127.0.0.2:7012, callback:org.apache.cassandra.service.WriteResponseHandler@d6593e7, invokeOnFailure:true})
		at org.apache.cassandra.net.RequestCallbacks.addWithExpiration(RequestCallbacks.java:99)
		at org.apache.cassandra.replication.TrackedWriteRequest.sendMessagesToRemoteDC(TrackedWriteRequest.java:287)
		at org.apache.cassandra.replication.ForwardedWrite$MutationRequest.applyLocallyAndForwardToReplicas(ForwardedWrite.java:285)
		at org.apache.cassandra.replication.ForwardedWrite$MutationRequest.applyLocallyAndForwardToReplicas(ForwardedWrite.java:200)
		at org.apache.cassandra.replication.ForwardedWrite$1.doVerb(ForwardedWrite.java:372)
		at org.apache.cassandra.net.InboundSink.lambda$new$0(InboundSink.java:103)
		at org.apache.cassandra.net.InboundSink$Filtered.accept(InboundSink.java:71)
		at org.apache.cassandra.net.InboundSink$Filtered.accept(InboundSink.java:57)
		at org.apache.cassandra.net.InboundSink.accept(InboundSink.java:123)
		... 6 common frames omitted